### ISSUE TITLE
Requirements have not been listed.

### ISSUE THREAD

**Issue by CraigglesO** [ebuchman/understanding_ethereum_trie#3]
Been downloading them individually.
pip install git+https://github.com/bjornedstrom/python-sha3
pip install bitcoin
pip install rlp

```
Traceback (most recent call last):
  File "ex1.py", line 3, in <module>
    import trie, utils, rlp
  File "../src/trie.py", line 5, in <module>
    import utils
  File "../src/utils.py", line 11, in <module>
    from rlp import big_endian_to_int, int_to_big_endian
ImportError: cannot import name big_endian_to_int
```

**Comment by CraigglesO** [comment]
os x : 
move examples to src folder

**Comment by dzwiener** [comment]
This issue is broken up into 2 problems. 1 you cannot find the utils, rlp, db and trie python files which you fixed. But then you also say that you need to download sha3 and bitcoin into the project. These modules are not provided to the user.
